@echo off
echo Installation des dépendances...

echo Exécution des ...................tests3..................
npx wdio wdio.conf.js --suite=feature3
echo Fiiiiiin Exécution des ................tests3........................

echo Exécution des .................tests1................
npx wdio wdio.conf.js --suite=feature1
echo Fiiiiiin Exécution des ........................tests1.................


echo Exécution des .....................tests2....................
npx wdio wdio.conf.js --suite=feature2
echo Fiiiiiin Exécution des .................tests2...
